/**
 * Constantes del módulo de ventas de sepulturas
 */

/**
 * Sistemas
 */
export const SISTEMA_VENTAS = 'VTA';
export const SISTEMA_COB = 'COB';
export const SISTEMA_ATC = 'ATC';
export const SISTEMA_SER = 'SER';

export const PARAMETRO_TIPO_UNIDAD_NEGOCIO = 'VTA_EMEG_TIPO_VTA';
export const DIAS_MAXIMOS_DE_RESERVA = 864000000; // 10 dias
export const DIRECCION_OTRO = 'CONT'; // Este es el valor del parametro GEN_DIR_FON_CONT

/**
 * Aplicaciones
 */
export const APLICACION_MANTENEDOR_SERVICIO = 'VtaMantSector';
export const APLICACION_MANTENEDOR_RECARGOS = 'VtaRcgoUbic';
export const APLICACION_MANTENEDOR_CARRERAS = 'VtaMantCarrera';
export const APLICACION_MANTENEDOR_UBICACIONES = 'VtaMantUbic';
export const APLICACION_MANTENEDOR_UBICACIONES_ATC = 'AtcMantUbic';
export const APLICACION_ADMIN_SEGURO = 'VtaAdmSeguro';
export const APLICACION_ADMIN_DESPACHO = 'VtaAdminDespa';
export const APLICACION_MANTENEDOR_TIPO_SECTOR = 'VtaMantTpoSector';
export const APLICACION_MANTENEDOR_PRECIOS = 'VtaMantPrecios';
export const APLICACION_MANTENEDOR_RESERVA_UBICACION = 'VtaRsvaUbic';
export const APLICACION_MANTENEDOR_OPERACIONES = 'VtaIngOpera';
export const APLICACION_MANTENEDOR_OPERACIONES_CAMBIO = 'VtaIngOpeCamb';
export const APLICACION_GENERADOR_UBICACION = 'VtaGeneUbic';
export const APLICACION_HABILIATACION_UBICACION = 'VtaHabiUbic';
export const APLICACION_MANTENEDOR_EMPLEADOS = 'GenMantEmpl';
export const APLICACION_STOCK_MAYOR = 'VtaAdmStockMa';
export const APLICACION_STOCK_MENOR = 'VtaAdmStockMe';
export const APLICACION_MANTENEDOR_CONVENIOS = 'VtaMantCvnio';
export const APLICACION_MANTENEDOR_FUENTES = 'VtaMantFnte';
export const APLICACION_ADMINISTRACION_DOCUMENTOS = 'GenAdmDctos';
export const APLICACION_ADMINISTRACION_MANDATOS = 'VtaAdmMndto';
export const APLICACION_INGRESO_ASEGURADOS = 'VtaIngAseg';
export const APLICACION_MANTENEDOR_DOCUMENTO = 'VtaMantDoc';
export const APLICACION_EMITIR_OPERACION = 'VtaEmitirOper';
export const APLICACION_MANTENEDOR_GRUPO_VENTA = 'VtaAdmGrpoVta';
export const APLICACION_INGRESO_OPERACION = 'VtaIngOpera';
export const APLICACION_MANTENEDOR_CONTRATOS = 'VtaMantContrato';
export const APLICACION_VERIFICACION_OPERACION = 'VtaVeriOper';
export const APLICACION_LISTA_CONTRATOS = 'VtaAplContrato';
export const APLICACION_MODIFICAR_CONTRATOS = 'VtaModifContrato';
export const APLICACION_CAMBIO_CONTRATOS = 'VtaIngRenegCont';
export const APLICACION_ADM_MANDATOS = 'CobAdmMandatos';
export const APLICACION_TRANSF_CONTRATOS = 'VtaIngrTransferencia';
export const APLICACION_EMISION_CONTRATOS = 'VtaEmitirOper';
export const APLICACION_MANTENEDOR_CUMPLIMIENTO_METAS = 'VtaMantCumplMetasVta';
export const APLICACION_MANTENEDOR_PERIODO_COMERCIAL = 'VtaMantPrdoCom';
export const APLICACION_MANTENEDOR_PERIODO_EMISION = 'VtaMantPrdoEmi';
export const APLICACION_ADMINISTRACION_PAGARE = 'VtaAdmPgre';
export const APLICACION_ADMINISTRACION_NOMINAS_FIRMA = 'VtaAdmNomFirma';
export const APLICACION_ADMINISTRACION_NOMINAS_DESPACHO = 'VtaAdmNomDesp';
export const APLICACION_LIBRO_IMPUESTO_TIMBRE = 'ConPrcImptoTimbre';
export const APLICACION_PROCESO_NOTIFICACION_SEGUROS = 'SerPrcNotiSeguros';
export const APLICACION_ADMINISTRACION_SINIESTROS = 'SegAdmRegSinies';
export const APLICACION_COMPANIA_SEGURO = 'SegMantCiaAseg';
export const APLICACION_GENERACION_SINIESTROS = 'SegGenSiniestro';
export const APLICACION_RESCILIACION_CONTRATOS = 'VtaResciliacionCont';
export const APLICACION_CONSULTA_CONTRATO = 'VtaConsContrato';
export const APLICACION_CONSULTA_CONTRATO_EXCEPCION = 'AplContExcepcion';
export const APLICACION_INGRESO_FUERZA_VENTAS = 'GenIngOrgResp';
export const APLICACION_PROVISION_VENTA_ESTADISTICA = 'GenProvVtaEstad';
export const APLICACION_COMISIONES = 'GenComisiones';
export const APLICACION_GEN_INGRESO_METAS = 'GenIngMetas';
export const APLICACION_GEN_CONSULTA_PRESUPUESTO = 'GenConPpto';
export const APLICACION_INGRESO_OPERACION_SVEP = 'VtaSVEPIngOpera';
export const APLICACION_DISTRIBUCION_DOCUMENTOS = 'DocDistribucion';
export const APLICACION_ASIGNACION_DOCUMENTOS = 'DocAsignacion';
export const APLICACION_CAMBIO_ESTADO_DOCUMENTOS = 'DocCambEstaDoc';
export const APLICACION_CONSULTA_ESTADO_DOCUMENTOS = 'DocConsDocto';
export const APLICACION_VENTA_TITULOS_CONVENIOS_CONTRATOS = 'VtaGenRegTitulo';
export const APLICACION_MANTENEDOR_UNIDADES_DOCUMENTOS = 'DocMantUnidades';
export const APLICACION_BASE_CERO_CINCO = 'VtaBaseCeroCinco';
export const APLICACION_PROCESO_CERO_CINCO = 'VtaPrdoProcResc';
export const APLICACION_AUTORIZACION_PAGARE_VENDIDO = 'VtaAutPgreVendido';
export const APLICACION_AUTORIZACION_UBICACION_CON_FALLECIDO = 'VtaAutContFallecido';
export const APLICACION_AUTORIZACION_CLIENTE_DEUDA = 'VtaAutClteDeuda';
export const APLICACION_INGRESO_METAS_GDN = 'VtaMetaGdn';
export const APICACION_REGULARIZACION_FUENTE = 'VtaRegFuente';
export const APLICTION_EXCEPCIONES_ADICIONAL = 'VtaExpMA';
export const APLICTION_RECHAZOS_DOCUMENTOS = 'VtaMantDocRechCont';
export const APLICTION_PORCENTAJE_SOBRE_PRECIO = 'VtaPrtjeSobrePrecio';

// PARDES-1312
export const APLICACION_ING_MANDATOS = 'CobIngrMandatos';

/**
 * PARDES-129 Reimpresion de Titulos: WEB crear nueva aplicacion
 */
export const APLICTION_REIMPRESION_TITULOS = 'VtaReimprTitulo';

// PARDES-280
export const APLICTION_PRDO_VTA_EMPR = 'VtaMantPrdoEmpr';

// PARDES-294
export const APLICTION_PRDO_VTA_UNEG = 'VtaMantPrdoUNEG';

// PARDES-399
export const APLICACION_ADM_GRUPO_FUENTE = 'VtaAdmGrpFuente';

// PARDES-402
export const APLICACION_ADM_TIOPO_PLAN = 'VtaAdmTipoPlan';

// PARDES-426
export const APLICACION_ADM_TASA_INTERES = 'VtaTasaInteres';

// PARDES-506
export const APLICACION_ADM_PARAM_MA = 'VtaAdmParamMA';

// PARDES-519
export const APLICACION_ADM_VTA_PARAM = 'VtaAdmPerfVenta';

// PARDES-583
export const APLICACION_SOLI_AUTO_GTECOME = 'VtaSolAutoGteCome';

// PARDES-583
export const APLICACION_SOLI_AUTO_GTEVTA = 'VtaSolAutoGteVenta';

// PARDES-583
export const APLICACION_SOLI_AUTO_JEFEVTA = 'VtaSolAutoJefeVenta';

// PARDES-583
export const APLICACION_SOLI_AUTO_SUPER = 'VtaSolAutoSupervisor';

// PARDES-681
export const APLICACION_ADM_GRUPO = 'VtaAdmGrupo';

export const APLICTION_PARAM_CONTRACTUALES = 'VtaPremCntrc';
export const APLICTION_ADM_CNAL_VERSUS_TIPO_PLAN = 'VtaAdmCanalTipoPlan';

export const DOMINIO_TIPO_ID = 'DM_TIPO_ID';
export const DOMINIO_UNIDAD_TIPO = 'DM_UNID_TIPO';
export const DOMINIO_UNIDAD_ESTADO_CODIGO = 'DM_UNID_ESTA_COD';
export const DOMINIO_ESTADO_EMPLEADO = 'DM_EMPL_ESTA_COD';
export const DOMINIO_NIVEL_EDUCACION = 'DM_NIVEL_EDUC';
export const DOMINIO_ESTADO_CIVIL = 'DM_EST_CIVIL';
export const DOMINIO_EMPLEADO_CARGO = 'DM_EMPL_CRGO';
export const DOMINIO_EMPL_ESTA_CONTRACTUAL = 'DM_EMPL_ESTA_CONT';
export const DOMINIO_MONEDA_VENTA = 'DM_MONE_COD_VTA';
export const DOMINIO_CONTRATO_TIPO = 'DM_CONT_TIPO';
export const DOMINIO_FONO_TIPO = 'DM_GEN_DIRE_FONO_TIPO';
export const DOMINIO_TEMPORALIDAD = 'DM_SEPU_TMP_PER';
export const DOMINIO_TIPO_SEPU_MATERIAL = 'DM_SEPU_TRRA_HORM';
export const DOMINIO_SEPUL_CARAC = 'DM_SEPUL_CARAC';
export const DOMINIO_TIPO_MANDATO_COB = 'DM_COB_MDTO_TIPO';
export const DOMINIO_BANCO_TIPOCTA = 'DM_BANCO_TIPOCTA';
export const DOMINIO_ESTADO_CAMBIO_CONT = 'DM_VTA_ESTA_CAMBCONT';
export const DOMINIO_ESTADO_TRANSFERENCIA = 'DM_VTA_ESTA_TRANSFERENCIA';

/**
 * Dominio
 */
export const DOMINIO_ESTADOS_OPERACION = 'DM_ESTA_OPER';
export const DOMINIO_PAC_PAT = 'DM_PAC_PAT';
export const DOMINIO_ESTADOS_SECTORES = 'DM_ESTA_COD';
export const DOMINIO_ESTADOS_SEPULTURA = 'DM_ESTA_COD';
export const DOMINIO_ESTADOS_RECARGOS = 'DM_ESTA_COD';
export const DOMINIO_ESTADOS_CODIGO = 'DM_ESTA_COD';
export const DOMINIO_ESTADOS_STOCKS = 'DM_ESTA_COD';
export const DOMINIO_ESTADOS_UBICACION = 'DM_UBIC_ESTA_COD';
export const DOMINIO_ESTADOS_CARRERA = 'DM_ESTA_COD';
export const DOMINIO_ESTADOS_CONVENIO = 'DM_CNVE_ESTA';
export const DOMINIO_ESTADOS_CONSTRUCCION = 'DM_UBIC_ESTA_CONS';
export const DOMINIO_TIPORECARGOS_RECARGOS = 'DM_TIPO_RCGO';
export const DOMINIO_TIPOVALORES_RECARGOS = 'DM_RCGO_TIPO_VALOR';
export const DOMINIO_CARACTERISTICAS_SEPULTURA = 'DM_SEPUL_CARAC';
export const DOMINIO_SI_NO = 'DM_SI_NO';
export const DOMINIO_TIPO_NECESIDAD = 'DM_NECE_TIPO';
export const DOMINIO_PIECUOTA = 'DM_PIE_CUOTA';
export const DOMINIO_TIPO_VENTA = 'DM_TIPO_VTA';
export const DOMINIO_TIPO_RECIBO = 'DM_COB_CMPR_TIPO';
export const DOMINIO_GRUPO_CONVENIO = 'DM_GRPO_CONV';
export const DOMINIO_FUENTE_CATEGORIA = 'DM_CAT_FNTE';
export const DOMINIO_GRUPO_FUENTE = 'DM_GRPO_FNTE';
export const DOMINIO_ESTADO_CODIGO = 'DM_ESTA_COD';
export const DOMINIO_ESTADO_PERIODO_CODIGO = 'DM_ESTA_COD';
export const DOMINIO_PORCENTAJE = 'UNTP_PORCENTAJE';
export const ESTADO_CONVENIO_VIGENTE = 'VIGENTE';
export const ESTADO_CONVENIO_SECTOR = 'VIGENTE';
export const ESTADO_OPERACION_VIGENTE = 'VIGENTE';
export const MONEDA_OPERACION = 'PESO';
export const MONEDA_PESO = 'PESO';
export const MONEDA_UF = 'UF';
export const DOMINIO_ESTADOS_COD = 'DM_ESTA_COD';
export const DOMINIO_ESTADOS_PERIODO_COMERCIAL = 'DM_ESTA_PRDO_COME';
export const DOMINIO_TIPO_DESTINO_DOC = 'DM_TIPO_DESTINO_DOC';
export const DOMINIO_PARENTESCO = 'DM_PARENTESCO';
export const DOMINIO_OPERACION_DIREC_TIPO = 'PART';
export const DOMINIO_TIPO_DESPACHO = 'DM_TIPO_DESP';
export const DOMINIO_FORMA_PAGO_CONT = 'DM_FRMA_PAGO_CONT';
export const DOMINIO_TIPO_MONEDA_CONT = 'DM_TIPO_MONE_CONT';
export const DOMINIO_CARGO_CAMBIO_CONT = 'DM_VTA_CARG_CAMB_CONT';
export const DOMINIO_TIPO_VERIFICACION = 'DM_TIPO_VERIF';
export const DOMINIO_TIPO_MANDATO = 'DM_PAC_PAT';
export const DOMINIO_MOTIVO = 'DM_MTVO_MANDATO';
export const DOMINIO_TIPO_CUENTA = 'DM_TIPO_CUENTA';
export const DOMINIO_BANCO = 'DM_GEN_BANCOS';
export const DOMINIO_TIPO_CUENTA_BANCO = 'DM_GEN_BANCO_TIPOCTA'; // Esto es terrible, sistema completamente en duro por estas maravillas.
export const DOMINIO_TIPOID = 'DM_TIPO_ID';
export const DOMINIO_PERIODICIDAD_CUOTA = 'DM_COB_PRDD_CUOTA';
export const DOMINIO_FORMA_PAGO = 'DM_FRMA_PAGO_DOC';
export const DOMINIO_PAC_CREDITOS = 'DM_PAC_CRED';
export const DOMINIO_PAC_MANTENCIONES = 'DM_PAC_MANT';
export const DOMINIO_TIPO_OPERACION = 'DM_TIPO_OPE';
export const DOMINIO_TIPO_OPERACION_MODIFICAR = 'DM_TIPO_OPE_MODIF';
export const DOMINIO_TIPO_SEXO = 'DM_TIPO_SEXO';
export const DOMINIO_TIPO_NACIONALIDAD = 'DM_TIPO_NAC';
export const DOMINIO_TIPO_DOCUMENTO = 'DM_FAM_DOC';
export const DOMINIO_TIPO_PERIODO = 'DM_TIPO_PERIODO';
export const ING = 'ING';
export const DOMINIO_TIPO_TARJETA = 'DM_TIPO_TJTA';
export const DOMINIO_EMISOR = 'DM_EMISOR';
export const DOMINIO_PAIS = 'DM_PAIS';
export const DOMINIO_ESTADO_MANDATO = 'DM_ESTA_MANDATO';
export const DOMINIO_ESTADOS_VENTA = 'DM_ESTA_COD';
export const DOMINIO_TIPO_SEGURO = 'DM_TIPO_SEGU';
export const DOMINIO_ESTADO_SINIESTRO = 'DM_ESTA_SINI';
export const DOMINIO_MESES = 'DM_MESES';
export const DOM_GEN_ESTADOS_CIVILES = 'DM_EST_CIVIL';
export const DOM_NIVELES_ESTUDIO = 'DM_NIVEL_EDUC';
export const DOMINIO_ESTADO_UBICACION_INGRESO_OPERACION = 'DM_ESTA_UBIC_ING_OPER';
export const DOMINIO_ESTADO_PERIODO_INGRESO = 'DM_ESTA_PRDO_INGR';
export const DOMINIO_NOMINAS_FIRMA_ESTADO_INGRESO = 'DM_NOMI_FIRMA_ESTA_INGR';
export const DOMINIO_NOMINAS_DESPACHO_ESTADO_INGRESO = 'DM_NOMI_DESPA_ESTA_INGR';
export const DOMINIO_CONCEPTOS = 'DM_SEG_CNCP_COD';
export const DOMINIO_ESTADO_APLICACION_SINIESTROS = 'DM_SEG_APL_SINI';
export const DOMINIO_DOCUMENTOS_SINIESTROS = 'DM_SEG_DCTO_COD';
export const DOMINIO_ESTADO_APLICACION_PREVENTA = 'DM_VTOP_ESTA_APLI_PREVENTA';
export const DOMINIO_TIPO_OPE_INGOPE = 'DM_SUB_TIPO_OPE_INGOPE';
export const DOMINIO_ESTADO_APLICACION_EMITIDO = 'NOEMITIDO';
export const DOMINIO_ESTADO_APLICACION_CAMBIO2 = 'DM_VTA_ESTA_OPER_CAMBIO2';
export const DOMINIO_TIPO_MODIFICACION_OPERACION = 'DM_TIPO_OPE_MODIF';
export const DOMINIO_TIPO_CAMBIO_CONTRATO = 'VTA_TIPO_OPE_CAMBCONT';
export const DOMINIO_ESTADO_MODIFICACION_OPERACION = 'DM_VTA_OPER_ESTA_MODIFCONT';
export const DOMINIO_OPERACION_SUBTIPO_CAMBIO_2 = 'DM_VTA_SUB_TIPO_CAMBIO2';
export const PARAMETRO_TIPO_OPERACION_RESCILIACION = 'VTA_TIPO_OPE_RESCILIACION';
export const DOMINIO_AUTORIZADOR_TRASLADO = 'DM_TRASLADO_AUT';
export const DOMINIO_AUTORIZADOR_CARTERA_VENDIDA = 'DM_PGRE_AUT_ANUL_VEND';
export const DOMINIO_MOTIVOS_RESCILIACION = 'DM_RESC_MTVO';
export const DOMINIO_AUTORIZADOR_TRANSFERENCIA = 'DM_TRANS_AUT';
export const DOMINIO_CONTRATO_VIGENTE = 'DM_VTA_CONT_VIGENTES';
export const DOMINIO_PERIODO_TIPO = 'DM_PRDO_TIPO';
export const DOMINIO_TIPO_LAPIDA = 'DM_SGLE_TIPO_LAP_COD';
export const DOMINIO_SUBTIPOS_SVEP = 'DM_SVEP_SUB_TIPO';
export const DOMINIO_UNIDAD_SUB_FAMILIA = 'DM_SUBFAM_DOCTO';
export const DOMINIO_CONCEPTO = 'DM_SEG_CNCP_COD';

/**
 * Titulos
 */
export const DOMINIO_ESTADO_PROCESOS_TITULO = 'DM_TCC_ESTA_COD';
export const DOMINIO_DM_CNDT_MINI_PIE_TIPO = 'DM_CNDT_MINI_PIE_TIPO';

/**
 * Parametros
 */
export const PARAMETRO_OPERACION_TRANSFERENCIA = 'VTA_TIPO_OPE_TRANSFERENCIA';
export const PARAMETRO_RECARGO_CONSOLIDADO = 'VTA_RCGO_TIPO_SECTOR';
export const PARAMETRO_ESTADO_VIGENTE = 'VTA_ESTADO_VIGENTE';
export const PARAMETRO_TIPO_SEPULTURA_CARRERA = 'VTA_ESTADO_VIGENTE';
export const PARAMETRO_PAC = 'PAC';
export const PARAMETRO_PAT = 'PAT';
export const PARAMETRO_TELEFONO_PART = 'PART';
export const PARAMETRO_TELEFONO_CELU = 'CELU';
export const PARAMETRO_CONT = 'CONT';
export const PARAMETRO_NAT = 'NAT';
export const PARAMETRO_EMPL = 'EMPL';
export const PARAMETRO_ESTADO_RESERVA_RESERVADA = 'VTA_UBIC_ESTA_RESERVADA';
export const PARAMETRO_ESTADO_RESERVA_HABILITADA = 'VTA_UBIC_ESTA_HABILITADA';
export const PARAMETRO_ESTADO_TIPORECARGOS_PRIME = 'PRIME';
export const PARAMETRO_TIPOSEPULTURA = 'MAUSOLEO';
export const PARAMETRO_TIPO_RESERVA = 'RSVA';
export const PARAMETRO_TIPO_ANULADA = 'ANUL';
export const PARAMETRO_NACIONALIDAD_NACIONAL = 'N';
export const PARAMETRO_NACIONALIDAD_INTERNACIONAL = 'I';
export const PARAMETRO_DIRECCION_COMERCIAL = 'COME';
export const PARAMETRO_DIRECCION_ESTADO_CONFIRMADO = 'CONFIRMADO';
export const PARAMETRO_PERSONA_ID_RUT = 'RUT';
export const PARAMETRO_PERSONA_ID_JUR = 'JUR';
export const PARAMETRO_ESTADO_RESERVA_VIGENTE = 'VTA_ESTADO_VIGENTE';
export const PARAMETRO_ESTADO_RESERVA_NOVIGENTE = 'VTA_ESTADO_NOVIGENTE';
export const PARAMETRO_ESTADO_CONVENIO_INGRESADO = 'VTA_CNVE_ESTA_INGRESADO';
export const PARAMETRO_NOVIGENTE = 'NOVIGENTE';
export const PARAMETRO_SI = 'SI';
export const PARAMETRO_NO = 'NO';
export const PARAMETRO_CONTRATO = 'CONTRATO';
export const PARAMETRO_PAGARE = 'PAGARE';
export const PARAMETRO_STOCKMAYOR = 'STOCKMAYOR';
export const PARAMETRO_STOCKMENOR = 'STOCKMENOR';
export const PARAMETRO_RECARGO_TIPO = 'VTA_RCGO_TIPO_PRIME';
export const PARAMETRO_ESTADO_DOM = 'VTA_ESTADO_VIGENTE';
export const PARAMETRO_DOCUMENTO_ESTADO_ANULADO = 'VTA_VTDO_ESTA_ANULADO';
export const PARAMETRO_HABILITADA = 'HABILITADA';
export const PARAMETRO_DOCUMENTO_ESTADO_SOLICITADO = 'VTA_VDOC_ESTA_SOLICITADO';
export const PARAMETRO_DOCUMENTO_ESTADO_STOCKMAYOR = 'VTA_VDOC_ESTA_STOCKMAYOR';
export const PARAMETRO_TIPO_PERSONA_CONT = 'VTA_PERS_TIPO_CONT_ASEGURADO';
export const PARAMETRO_TIPO_ERR_CONT_OBS = 'VTA_TIPO_ERR_CONT_OBS';
export const PARAMETRO_TIPO_DCTO_PAGARE = 'GEN_DCTO_PAGARE';
export const PARAMETRO_TIPO_DOCTO_CONTRATO = 'GEN_TIPO_DOCTO_VTA_CONT';
export const PARAMETRO_TIPO_DOCTO_SINIESTRO = 'SEG_FLED_TIPO_DOC_SINIESTRO';
export const PARAMETRO_TIPO_TITULAR = 'VTA_VPET_TIPO_TITULAR';
export const PARAMETRO_VTOP_ESTA_PREVENTA = 'VTA_VTOP_ESTA_PREVENTA';
export const PARAMETRO_VTOP_ESTA_ENTRAMITE = 'VTA_VTOP_ESTA_ENTRAMITE';
export const PARAMETRO_VTOP_ESTA_INGRESADO = 'VTA_VTOP_ESTA_INGRESADO';
export const PARAMETRO_VPET_TIPO_TITULAR = 'VTA_VPET_TIPO_TITULAR';
export const PARAMETRO_CONT_FRMA_PAGO_CREDITO = 'VTA_CONT_FRMA_PAGO_CREDITO';
export const PARAMETRO_OPERACION_RECHAZADO = 'VTA_VTOP_ESTA_RECHAZADO';
export const PARAMETRO_POSI_DOC_STOCKMAYOR = 'VTA_POSI_DOC_STOCKMAYOR';
export const PARAMETRO_POSI_DOC_STOCKMENOR = 'VTA_POSI_DOC_STOCKMENOR';
export const PARAMETRO_POSI_DOC_USUARIO = 'VTA_POSI_DOC_USUARIO';
export const PARAMETRO_EMPL_CRGO_JEFEDEVENTA = 'GEN_EMPL_CRGO_JEFEDEVENTA';
export const PARAMETRO_EMPL_CRGO_SUPERVISOR = 'GEN_EMPL_CRGO_SUPERVISOR';
export const PARAMETRO_EMPL_CRGO_VENDEDOR = 'GEN_EMPL_CRGO_VENDEDOR';
export const PARAMETRO_DOMINIO_ESTADO_CONTRATO = 'DM_CONT_ESTA_APLCONT';
export const PARAMETRO_DOMINIO_ESTADO_PAGARE = 'DM_CONT_ESTA_APLPGRE';
export const PARAMETRO_DOMINIO_ESTADO_CONTRATO_APROBADO = 'VTA_VTOP_ESTA_APROBADO';
export const PARAMETRO_NOMINA_TIPO_FIRMA = 'VTA_NOMI_TIPO_FIRMA';
export const PARAMETRO_NOMINA_TIPO_DESPACHO = 'VTA_NOMI_TIPO_DESPACHO';
export const PARAMETRO_NOMINA_ESTADO_CERRADO = 'VTA_NOMI_ESTA_CERRADO';
export const PARAMETRO_CIA_ESTA_INGRESADO = 'SEG_CIA_ESTA_INGRESADO';
export const PARAMETRO_CONSULTA = 'CONSULTA';
export const PARAMETRO_DESPACHADO = 'DESPACHADO';
export const PARAMETRO_ESTADO_OPERACION_PRELIMINAR = 'VTA_VTOP_ESTA_PRELIMINAR';
export const PARAMETRO_ESTADO_OPERACION_ANULADA = 'VTA_VTOP_ESTA_ANULADO';
export const PARAMETRO_ESTADO_OPERACION_PREVENTA = 'VTA_VTOP_ESTA_PREVENTA';
export const PARAMETRO_ESTADO_OPERACION_ENVIADO = 'VTA_VTOP_ESTA_ENVIADO';
export const PARAMETRO_ESTADO_OPERACION_INGRESADO = 'VTA_VTOP_ESTA_INGRESADO';
export const PARAMETRO_ESTADO_OPERACION_RECHAZADO = 'VTA_VTOP_ESTA_RECHAZADO';
export const PARAMETRO_ESTADO_OPERACION_GENERADO = 'VTA_VTOP_ESTA_GENERADO';
export const PARAMETRO_MALLA_ESTADO = 'ESTA_DESP';
export const PARAMETRO_TIPO_OPERACION_NUEVA = 'VTA_TIPO_OPE_VENTANUEVA';
export const PARAMETRO_TIPO_OPERACION_MODIFICACION_CONTRATO = 'VTA_TIPO_OPE_MODIFCONT';
export const PARAMETRO_TIPO_OPERACION_CAMBCONT = 'VTA_TIPO_OPE_CAMBCONT';
export const PARAMETRO_ESTADO_GENERADA = 'VTA_UBIC_ESTA_GENERADA';
export const PARAMETRO_CONTEXTO_INGR = 'INGR';
export const PARAMETRO_CONTEXTO_REGU = 'REGU';
export const PARAMETRO_MALLA_CONTRATO_DESPACHO = 'CONTDESP';
export const PARAMETRO_EMPLEADO_CARGO_VENDEDOR = 'GEN_EMPL_CRGO_VENDEDOR';
export const PARAMETRO_EMPLEADO_CARGO_EMPLEADO = 'GEN_EMPL_CRGO_EMPLEADO';
export const PARAMETRO_MALLA_SINIESTRO = 'SEG_FLED_TIPO_DOC_SINIESTRO';
export const PARAMETRO_SUBTIPO_OPERACION_CAMBIO_TITULAR = 'VTA_SUB_TIPO_OPER_CAMBTITU';
export const PARAMETRO_SUBTIPO_OPERACION_CAMBIO_UBICACION = 'VTA_SUB_TIPO_OPER_CAMBUBIC';
export const PARAMETRO_PERIODICIDAD_MENSUAL = 'COB_PRDD_CUOTA_MENSUAL';
export const PARAMETRO_PERIODO_TIPO_COMERCIAL = 'VTA_PRDO_TIPO_COMERCIAL';
export const PARAMETRO_PERIODO_TIPO_CONTABLE = 'VTA_PRDO_TIPO_CONTABLE';
export const PARAMETRO_PERIODO_TIPO_EMISION = 'VTA_PRDO_TIPO_EMISION';
export const PARAMETRO_ESTADO_PERIODO_EN_CURSO = 'VTA_PRDO_COME_CONT_ENCURSO';
export const PARAMETRO_GEN_PROCESO_CONTABLE = 'GEN_PROCESO_CONTABLE';
export const PARAMETRO_GENERAL_PAIS_DEFAULT = 'GEN_PAIS_DEFAULT';
export const PARAMETRO_RCGO_TIPO_UBICACION = 'VTA_RCGO_TIPO_UBICACION';
export const PARAMETRO_TITULAR_CONTRATO_VIGENTE = 'VTA_COTI_ESTA_VIGENTE';
export const PARAMETRO_TITULAR_CONTRATO_EN_PROCESO = 'VTA_COTI_ESTA_ENPROCESO';
export const PARAMETRO_VTA_TIPO_VTA_CREDITO = 'VTA_TIPO_VTA_CREDITO';
export const PARAMETRO_VTA_ESTADO_EMITIDO = 'VTA_VTOP_ESTA_EMITIDO';
export const PARAMETRO_VTA_ESTADO_RECHAZADO = 'VTA_VTOP_ESTA_RECHAZADO';
export const PARAMETRO_VTA_ESTADO_ENVIADO = 'VTA_VTOP_ESTA_ENVIADO';
export const PARAMETRO_VTA_PRDO_COME_CONT_CERRADO = 'VTA_PRDO_COME_CONT_CERRADO';
export const PARAMETRO_VTA_PRDO_COME_CONT_ENCIERRE = 'VTA_PRDO_COME_CONT_ENCIERRE';
export const PARAMETRO_PRDO_NUM = 'VTA_PRDO_NUM';
export const PARAMETRO_ESTADO_INICIAL_SERIE = 'VTA_ESTADO_VIGENTE';

/**
 * Codigos validacion modificacion contrato (VTA_VAL_CONT_MODIF)
 */
export const CODIGO_MODIFICACION_CONTRATO_CAMBIO_ESTADO = 'CAMBESTA';
export const CODIGO_MODIFICACION_CONTRATO_REGULARIZAR = 'CONT';
export const CODIGO_MODIFICACION_CONTRATO_ASEGURADO = 'ASEG';
export const CODIGO_MODIFICACION_CONTRATO_MANDATO = 'MDTO';
export const CODIGO_VALIDAR_CONTRATO_IMPRESION = 'IMPR';

/**
 * Codigos validadcion Titulos Contratos y Convenios (VTA_VAL_TCC_MASIVO)
 */
export const CODIGO_TCC_IMPRIMIR_MASIVO = 'MIMPR';
export const CODIGO_TCC_IMPRIMIR_INDIVIDUAL = 'IMPRIMIR';
export const CODIGO_TCC_IMPRIMIR_DOMINIO = 'TITULO_DOMINIO';
export const CODIGO_TCC_CAMBIO_ESTADO_MASIVO = 'MESTA';
export const CODIGO_TCC_ANULAR = 'ANULAR';
export const CODIGO_TCC_ASIGNAR = 'ASIGNAR';
export const CODIGO_TCC_CAMBIO_ESTADO = 'CAMBESTA';

/**
 * Codigos de impresion Titulos Contratos y Convenios
 */
export const CODIGO_TCC_IMPRIMIR_CONVENIO = 'CONVENIO';
export const CODIGO_TCC_IMPRIMIR_COMPRAVENTA = 'CMPRVTA';

/**
 * Parametros Documentos (DOCPAR)
 */
export const PARAMETRO_DOCTO_SUB_FAMILIA_RECIBO = 'DOC_SUB_FAMI_RECIBO';
export const PARAMETRO_DOCTO_SUB_FAMILIA_PAGARE = 'DOC_SUB_FAMI_PAGARE';
export const PARAMETRO_DOCTO_TIPO_MANUAL = 'DOCTO_TIPO_MANUAL';

/**
 * Parametros General (GENPAR)
 */
export const PARAMETRO_GEN_ESTADO_VIGENTE = 'GEN_ESTA_COD_VIGENTE';

/**
 * Otros
 */
export const VERSION_INICIAL = 1;
export const ORIGEN_VALIDACION_OPERACION_BASICA = 'BASICA';
export const FORMA_PAGO_CONTADO = 'CONTADO';
export const FORMA_PAGO_CREDITO = 'CREDITO';
export const INDICADOR_PIE_CUOTA_PIE = 'PIE';

/**
 * Operaciones Periodo Contable
 */
export const OPERACION_PERIODO_CONTABLE_CERRAR = 'C';
export const OPERACION_PERIODO_CONTABLE_ABRIR = 'A';

/**
 * Contextos convenio
 */
export const CONTEXTO_CONVENIO_REGULARIZAR = 'REGU';
export const CONTEXTO_CONVENIO_VER_DETALLE = 'DETA';
export const CONTEXTO_CONVENIO_CAMBIO_ESTADO = 'ESTA';
export const CONTEXTO_MANDATO = 'MANDATO';

/**
 * Contextos nomina
 */
export const CONTEXTO_NOMINA_REGULARIZAR = 'REGU';
export const CONTEXTO_NOMINA_RESPUESTA = 'RESP';
export const CONTEXTO_NOMINA_CERRAR = 'CERR';

/**
 * Contextos email
 */
export const CONTEXTO_MAIL_FIRMA_NOMINAS = 'NOMIFIRMA';

/**
 * Tipos de documentos
 */
export const TIPO_DOCUMENTO_CONVENIO = 'CONVENIO';

/**
 * Tipos de proceso nominas
 */
export const TIPO_PROCESO_NOMINA_ENVIAR = 'ENV';
export const TIPO_PROCESO_NOMINA_GENERAR = 'GEN';
export const TIPO_PROCESO_NOMINA_DESPACHAR = 'DESP';

/**
 * Tipos de proceso libro impuesto timbre
 */
export const TIPO_PROCESO_LIBRO_IMPUESTO_GENERAR = 'GEN';
export const TIPO_PROCESO_LIBRO_IMPUESTO_EMITIR = 'EMI';

/**
 * Tipos de proceso de proceso de notificacion de seguros
 */
export const TIPO_PROCESO_NOTIFICACION_SEGURO_GENERAR = 'GEN';
export const TIPO_PROCESO_NOTIFICACION_SEGURO_EMITIR = 'EMI';

/**
 * Tipos de proceso de administracion de siniestros
 */
export const TIPO_PROCESO_SINIESTRO_REGENERAR = 'RGEN';
export const TIPO_PROCESO_SINIESTRO_REGENERAR2 = 'REGEN';
export const TIPO_PROCESO_GENERAR_SINIESTROS = 'GEN';

/**
 * Tipo Direcciones
 */
export const TIPO_DIRE_COMERCIAL = 'COME';
export const TIPO_DIRE_PARTICULAR = 'PART';
export const TIPO_DIRE_OTRA = 'CONT';

/**
 * Tipo Documentos
 */
export const TIPO_DOC_CONTRATO = 'CONT';
export const TIPO_DOCUMENTO_TITULO = 'TITULO';
export const TIPO_ESTADO_TITULO = 'TCC_TIT';

/**
 * ORDES LST
 */
export const ORDEN_LISTA_TIPO_SECTOR = '1';
export const ORDEN_LISTA_SECTOR = '2';
export const ORDEN_LISTA_UBICACION = '5';
export const ORDEN_LISTA_DOMINIO = '2';
export const ORDEN_LISTA_PRECIO = '1';
export const ORDEN_LISTA_SEPULTURA = '1';

export const REPORTE_IMPRESION_TITULO = 'TITULO_DOMINIO';
export const REPORTE_IMPRESION_TITULO_MASIVO = 'IMP_TITULO_DOMINIO_MASIVO';
export const REPORTE_IMPRESION_CONVENIO = 'TITULO_CONVENIO';
export const REPORTE_IMPRESION_COMPRAVENTA = 'TITULO_COMPRAVENTA';

export const APLICACION_VENTA_TITULOS_VGRT = 'VtaGenRegTitulo';
export const APLICACION_VENTA_TITULOS_VTRT = 'VtaTesRegTitulo';
export const APLICACION_VENTA_TITULOS_VRRT = 'VtaRevRegTitulo';
export const APLICACION_VENTA_TITULOS_VGerRT = 'VtaGteRegTitulo';
export const APLICACION_VENTA_TITULOS_VPRT = 'VtaPdteRegTitulo';
export const APLICACION_VENTA_TITULOS_VEETRT = 'VtaEETRegTitulo';
export const APLICACION_MANTENEDOR_UNIDADES = 'DocMantUnidades';
export const APLICACION_VALOR_CUBIERTO_SMAD = 'MantValCubSMAD';
export const TIPO_PROCESO_NOTIFICACION_SEGURO_ARCHIVO = 'ARCH';
export const APLICACION_ADMINISTRACION_POLIZA = 'SegAdmPolizas';
export const DM_SEG_CNCP_COD = 'DM_SEG_CNCP_COD';
export const DM_PLZA_PRDO_CAREN_TIPO = 'DM_PLZA_PRDO_CAREN_TIPO';
export const DM_SEG_MANT_MODO = 'DM_SEG_MANT_MODO';
export const APLICACION_OPER_SUSCRIPCION_POLIZA = 'SegOperSuscrPLZA';
export const COB_DM_OPER_SUSCRIPCION = 'COB_DM_OPER_SUSCRIPCION';
export const COB_TIPO_DOCTO_OPER_SUSCR = 'COB_SUSCR';
export const SUSC_ORIGEN = 'SUSCRIPCION';
export const COMPUTACIONAL = 'COMPUTACIONAL';

