/**
 * Constantes del módulo de documentos
 */

/**
 * Parametros
 */
export const PARAMETRO_TIPO_UNIDAD_NEGOCIO = 'GEN_EMEG_TIPO_FUN';
export const SISTEMA_DOCUMENTO = 'DOC';
export const APLICACION_ASIGNACION_DOCUMENTOS = 'DocAsignacion';
export const APLICACION_CAMBIO_ESTADO_DOCUMENTOS = 'DocCambEstaDoc';
export const APLICACION_CONSULTA_ESTADO_DOCUMENTOS = 'DocConsDocto';
export const APLICACION_DISTRIBUCION_DOCUMENTOS = 'DocDistribucion';
export const APLICACION_GENERACION_DOCUMENTOS = 'DocGeneracion';
export const APLICACION_MANTENEDOR_UNIDADES_DOCUMENTOS = 'DocMantUnidades';
export const APLICACION_MANTENEDOR_UNIDADES = 'DocMantUnidades';
export const PARAMETRO_ESTADO_INICIAL_SERIE = 'VTA_ESTADO_VIGENTE';
export const DOMINIO_TIPO_DOCUMENTO = 'DM_FAM_DOC';
export const ORDEN_LISTA_DOMINIO = '2';
export const PARAMETRO_CONTRATO = 'CONTRATO';
export const PARAMETRO_PAGARE = 'PAGARE';
export const DOMINIO_ESTADOS_CODIGO = 'DM_ESTA_COD';
export const DOMINIO_TIPO_NECESIDAD = 'DM_NECE_TIPO';
export const DOMINIO_FORMA_PAGO = 'DM_FRMA_PAGO_DOC';
export const DOMINIO_UNIDAD_TIPO = 'DM_UNID_TIPO';
export const DOM_GEN_ESTADOS_CIVILES = 'DM_EST_CIVIL';
export const DOM_NIVELES_ESTUDIO = 'DM_NIVEL_EDUC';
export const PARAMETRO_DOC_UNID_TIPO_MAYOR = 'DOC_UNID_TIPO_MAYOR';
export const PARAMETRO_EMPLEADO_CARGO_VENDEDOR = 'GEN_EMPL_CRGO_VENDEDOR';
export const PARAMETRO_EMPLEADO_CARGO_EMPLEADO = 'GEN_EMPL_CRGO_EMPLEADO';
export const PARAMETRO_TELEFONO_PART = 'PART';
export const PARAMETRO_TELEFONO_CELU = 'CELU';
export const PARAMETRO_CONT = 'CONT';
export const PARAMETRO_NAT = 'NAT';
export const PARAMETRO_EMPL = 'EMPL';
export const VERSION_INICIAL = 1;
export const DOMINIO_EMPL_ESTA_CONTRACTUAL = 'DM_EMPL_ESTA_CONT';
export const DOMINIO_EMPLEADO_CARGO = 'DM_EMPL_CRGO';
export const DOMINIO_TIPO_NACIONALIDAD = 'DM_TIPO_NAC';
export const DOMINIO_ESTADO_CIVIL = 'DM_EST_CIVIL';
export const DOMINIO_NIVEL_EDUCACION = 'DM_NIVEL_EDUC';
export const DOMINIO_TIPO_SEXO = 'DM_TIPO_SEXO';
export const DOMINIO_ESTADO_EMPLEADO = 'DM_EMPL_ESTA_COD';
export const DOMINIO_TIPO_ID = 'DM_TIPO_ID';
export const DOMINIO_CARGO_CAMBIO_CONT = 'DM_VTA_CARG_CAMB_CONT';
